name = "discord-slash-commands"
main = "src/index.ts"
compatibility_date = "2023-01-13"
node_compat = true
[vars]
[triggers]
crons = ["0 */12 * * *"]
# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 1