name: pre-merge-checks
on:
  push:
    branches: test/issue#257-2
jobs:
  Lint-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint-check
      - run: npm run format-check
      - run: cat src/index.ts
      - run: cat config/envVarCheck.ts
      - run: npm run format-fix
      - run: cat src/index.ts
      - run: cat config/envVarCheck.ts